version: v59
mysql:
  host: ''
  port: ''
  user: ''
  pass: ''
  base: ''
  prefix: betonquest_
language: de
update:
  enabled: true
  download_bugfixes: true
  notify_new_release: true
  notify_dev_build: true
default_journal_slot: '-1'
max_npc_distance: '4'
citizens_npcs_by_name: 'false'
default_conversation_IO: tellraw
display_chat_after_conversation: 'true'
default_interceptor: simple
combat_delay: '5'
notify_pullback: 'true'
default_package: utilities
remove_items_after_respawn: 'true'
quest_items_unbreakable: 'true'
sounds:
  start: ENTITY_VILLAGER_AMBIENT
  end: ENTITY_VILLAGER_YES
  journal: ENTITY_BAT_TAKEOFF
  update: 'false'
  full: 'false'
cmd_blacklist:
- spawn
hook:
  citizens: 'true'
  mythicmobs: 'true'
  vault: 'true'
  worldguard: 'true'
  skript: 'false'
  mcmmo: 'false'
  effectlib: 'false'
  playerpoints: 'false'
  heroes: 'false'
  magic: 'false'
  denizen: 'false'
  skillapi: 'false'
  quests: 'false'
  shopkeepers: 'false'
  placeholderapi: 'false'
  holographicdisplays: 'true'
  racesandclasses: 'false'
  legendquest: 'false'
  worldedit: 'true'
  betonlangapi: 'true'
  bountifulapi: 'false'
  protocollib: 'true'
  brewery: 'false'
  jobsreborn: 'true'
journal:
  chars_per_line: '19'
  lines_per_page: '13'
  one_entry_per_page: 'false'
  reversed_order: 'true'
  hide_date: 'false'
  full_main_page: 'false'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
conversation_colors:
  npc: dark_red
  player: dark_green
  text: red,italic
  answer: green,italic
  number: white
  option: aqua
date_format: dd.MM.yyyy HH:mm
packages:
- monthly
- weeklys
- dailys
- utilities
- single
- default
debug: 'false'
